# .coderabbit.yaml — Origin Vault

language: "en-US"

reviews:
  profile: "chill"                       # reduce nit noise
  high_level_summary: true
  commit_status: true

  # Review code + important markdown, ignore vault "noise"
  path_filters:
    # Code + templates
    - "99-System/Scripts/**"
    - "99-System/Templater/**"
    - "99-System/QuickAdd/**"
    - "99-System/Templates/**"
    - "scripts/**"
    - "tools/**"
    - "**/*.py"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.md"

    # Exclude vault chatter / heavy assets
    - "!**/.obsidian/**"
    - "!**/Attachments/**"
    - "!**/imagegrid/**"
    - "!**/Images/**"
    - "!**/PDFs/**"
    - "!06-Archive/**"
    - "!05-Calendar/**"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.webp"

  path_instructions:
    - path: "99-System/Scripts/**/*.py"
      instructions: |
        Treat as CLI utilities run from the vault root. Prefer pure functions + argparse.
        UTF-8 I/O; never clobber files without a --dry-run; print a summary of changes.
        When editing Markdown, PRESERVE YAML frontmatter order/keys and Dataview/Tasks code fences.
        Never hardcode secrets or absolute paths; support Windows/macOS path separators.

    - path: "99-System/Scripts/**/*.js"
      instructions: |
        General Node/utility JS: keep modules small; no blocking I/O; handle missing env safely.
        Do not touch .obsidian/workspace* files. Avoid absolute paths and hardcoded vault names.

    - path: "99-System/Templater/**/*.js"
      instructions: |
        Templater user scripts must be Obsidian-safe: use async/await; fail safe on mobile.
        Do not mutate workspace/layout. Access tp/app defensively; catch and surface errors.
        No long-running loops; prefer small helpers users can compose in templates.

    - path: "99-System/QuickAdd/**/*.json"
      instructions: |
        QuickAdd macros/config: validate file moves/writes are idempotent and reversible.
        Flag any steps that could duplicate notes or drop YAML. No secrets in config fields.

    - path: "99-System/Templates/**/*.md"
      instructions: |
        These are note templates. Do NOT "fix" Templater tags (<% %>) or QuickAdd placeholders.
        Keep YAML frontmatter keys intact (title, type, status, created, modified, tags, maturity).
        Suggest improvements only if they reduce user friction or fix correctness.

    - path: "**/*.md"
      instructions: |
        Treat as docs. Preserve YAML frontmatter keys/values (including emojis) and order.
        Do not rewrite Dataview/Tasks/Templater code fences unless a clear bug is present.
        Only propose lint fixes that improve clarity or fix broken links/anchors.

  auto_review:
    enabled: true
    auto_incremental_review: true
    # Optionally gate to avoid content-only PRs:
    # labels: ["automation", "scripts", "templater", "quickadd", "!docs"]
    ignore_usernames: ["dependabot[bot]", "renovate[bot]", "OV-Codex[bot]"]

  pre_merge_checks:
    title:
      mode: "warning"
      requirements: "Use Conventional Commits (type(scope): subject)."

tools:
  eslint: { enabled: true }
  ruff: { enabled: true }
  markdownlint: { enabled: true }
  yamllint: { enabled: true }
  gitleaks: { enabled: true }   # flags secrets in diffs

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      # Make your vault rules available to the reviewer as context
      - "**/My PKM Metadata.md"
      - "**/Master PKM System Overview.md"
      - "**/My PKM Folders.md"
      - "**/VALUES of Metadata.md"
      - "**/My PKM Workflows - Global Guidelines.md"
      # Any repo-wide style docs you keep
      - "**/.cursorrules"
      - "**/CLAUDE.md"
      - "docs/STYLE*.md"
      - "Codex/**/GUIDELINES*.md"
